# Expand local shader includes at build time: a consuming app needs no source files.
# Each local file is included once; system includes stay for the Metal compiler.
function(expand_shader path result)
  get_filename_component(path "${path}" REALPATH)
  get_property(seen GLOBAL PROPERTY shader_includes)
  if("${path}" IN_LIST seen)
    set(${result} "" PARENT_SCOPE)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY shader_includes "${path}")
  file(READ "${path}" source)
  get_filename_component(dir "${path}" DIRECTORY)
  get_filename_component(name "${path}" NAME)
  string(REGEX MATCHALL "#include[ \t]+\"[^\"]+\"" includes "${source}")
  foreach(include IN LISTS includes)
    string(REGEX REPLACE "#include[ \t]+\"([^\"]+)\"" "\\1" local "${include}")
    expand_shader("${dir}/${local}" expanded)
    string(REPLACE "${include}" "${expanded}" source "${source}")
  endforeach()
  string(REPLACE "#pragma once" "" source "${source}")
  set(${result} "\n// ${name}\n${source}\n" PARENT_SCOPE)
endfunction()

cmake_policy(SET CMP0057 NEW)
expand_shader("${INPUT}" text)
get_filename_component(output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE ${OUTPUT}
  "#pragma once\n// Generated from ${INPUT}; do not edit.\ninline constexpr const char ${SYMBOL}[] = R\"SPLATKIT(${text})SPLATKIT\";\n")
